services:
  web:
    image: 014420964444.dkr.ecr.ap-northeast-1.amazonaws.com/fitcal-web:v1.1
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    depends_on:
      - db
      - redis
    expose:
      - 8000
    restart: on-failure
    command: >
      sh -c "python manage.py migrate &&
             gunicorn fitcal.wsgi:application --bind 0.0.0.0:8000 --workers=3"

  db:
    image: postgis/postgis:17-3.4
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: on-failure

  redis:
    image: redis:7-alpine
    expose:
      - "6379"
    restart: on-failure

  celery:
    image: 014420964444.dkr.ecr.ap-northeast-1.amazonaws.com/fitcal-celery:v1.1
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: celery -A fitcal worker -l info
    env_file:
      - .env
    depends_on:
      - redis
      - db
    restart: on-failure

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/staticfiles
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - web
    restart: on-failure

volumes:
  pgdata:
