# Generated by Django 5.2.1 on 2025-05-23 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_cart_member'),
        ('members', '0008_alter_member_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='members.member'),
        ),
    ]
