# Generated by Django 5.2.1 on 2025-06-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_keyword', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
        ),
    ]
