# Generated by Django 5.2 on 2025-05-06 02:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='name',
        ),
        migrations.AlterField(
            model_name='store',
            name='tax_id',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$', message='統編必須為8位數字')]),
        ),
    ]
