# Generated by Django 5.2.1 on 2025-05-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_closing_time_store_opening_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='name',
            field=models.CharField(default='未命名商家', max_length=50),
            preserve_default=False,
        ),
    ]
