# Generated by Django 5.2.1 on 2025-05-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_member_gender'),
        ('stores', '0005_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('member', 'store'), name='unique_member_store'),
        ),
    ]
