# Generated by Django 5.2.1 on 2025-05-31 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_alter_rating_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='store_covers/'),
        ),
        migrations.AddField(
            model_name='store',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='store_logos/'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
