# Generated by Django 5.2.1 on 2025-06-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_remove_rating_unique_member_store_store_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='store_covers/'),
        ),
        migrations.AddField(
            model_name='store',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='store_logos/'),
        ),
    ]
