# Generated by Django 5.2.1 on 2025-06-09 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_alter_collection_product'),
        ('orders', '0009_pendingorder'),
        ('stores', '0010_category'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rating',
            name='unique_member_store_rating',
        ),
        migrations.AddField(
            model_name='rating',
            name='order',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('order',), name='unique_rating_per_order'),
        ),
    ]
