# Generated by Django 5.2.1 on 2025-06-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
