# Generated by Django 5.2.1 on 2025-05-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_ordered_stores'),
        ('orders', '0003_alter_order_product'),
        ('products', '0008_product_store'),
        ('stores', '0002_store_closing_time_store_opening_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='products',
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('member', 'store')},
        ),
        migrations.AddField(
            model_name='order',
            name='member_phone',
            field=models.CharField(editable=False, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_number',
            field=models.CharField(editable=False, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='store_address',
            field=models.CharField(editable=False, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='store_phone',
            field=models.CharField(editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PENDING', '待付款'), ('CANCELED', '已取消'), ('PREPARING', '準備中'), ('READY', '餐點已備妥'), ('COMPLETED', '已完成'), ('NO_SHOW', '未取餐'), ('CANCELED_REFUNDED', '已取消 (退款)')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product')},
        ),
        migrations.RemoveField(
            model_name='order',
            name='customize',
        ),
    ]
