# Generated by Django 5.2.1 on 2025-05-18 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_product_order_products_and_more'),
        ('stores', '0002_store_closing_time_store_opening_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='member_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='member_phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='store_name',
        ),
        migrations.AlterField(
            model_name='order',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='stores.store'),
        ),
    ]
