# Generated by Django 5.2.1 on 2025-05-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_member_name_remove_order_member_phone_and_more'),
        ('products', '0008_product_store'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PENDING', '待付款'), ('CANCELED', '已取消'), ('PREPARING', '準備中'), ('READY', '餐點已備妥'), ('COMPLETED', '已完成'), ('NO_SHOW', '未取餐'), ('CANCELED_REFUNDED', '已取消並退款')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH', '現金'), ('CREDIT_CARD', '信用卡'), ('LINE_PAY', 'LINE Pay')], default='CASH', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', '未付款'), ('PAID', '已付款'), ('REFUNDED', '已退款')], default='UNPAID', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'product'), name='unique_order_product'),
        ),
    ]
