# Generated by Django 5.2.1 on 2025-05-22 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_collection_member_favorite_products_and_more'),
        ('orders', '0006_alter_order_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='member_name',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='member_phone',
            field=models.CharField(editable=False, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='store_name',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='members.member'),
        ),
    ]
