# Generated by Django 5.2.1 on 2025-05-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_member_name_order_member_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PENDING', '處理中'), ('CANCELED', '已取消'), ('PREPARING', '準備中'), ('READY', '餐點已備妥'), ('COMPLETED', '已完成'), ('NO_SHOW', '未取餐'), ('CANCELED_REFUNDED', '已取消並退款')], default='PENDING', max_length=20),
        ),
    ]
