# Generated by Django 5.2.1 on 2025-06-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='canceled_by',
            field=models.CharField(blank=True, choices=[('MEMBER', '會員取消'), ('STORE', '店家取消'), ('SYSTEM', '系統自動取消')], max_length=10, null=True),
        ),
    ]
