# Generated by Django 5.2.2 on 2025-06-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_canceled_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH', '現金'), ('LINE_PAY', 'LINE Pay')], default='CASH', max_length=20),
        ),
    ]
