# Generated by Django 5.2.2 on 2025-06-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
