# Generated by Django 5.2.1 on 2025-05-20 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<<< HEAD:members/migrations/0005_favorite_member_favorite.py
        ('members', '0004_alter_member_phone_number'),
        ('stores', '0004_store_closing_time_store_opening_time'),
========
        ('members', '0003_member_ordered_stores'),
        ('stores', '0002_store_closing_time_store_opening_time'),
>>>>>>>> c6368d9 (feat: implement store-member favorite relationship and fix logic):members/migrations/0004_favorite_member_favorite.py
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_records', to='members.member')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
            options={
                'unique_together': {('member', 'store')},
            },
        ),
        migrations.AddField(
            model_name='member',
            name='favorite',
            field=models.ManyToManyField(related_name='favorited_by', through='members.Favorite', to='stores.store'),
        ),
    ]
