# Generated by Django 5.2.1 on 2025-05-18 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_ordered_stores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='ordered_stores',
        ),
    ]
