# Generated by Django 5.2 on 2025-05-14 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_favorite_member_favorite'),
        ('stores', '0002_store_closing_time_store_opening_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='store',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
    ]
