# Generated by Django 5.2.1 on 2025-05-21 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_favorite_member_favorite'),
        ('members', '0007_merge_20250516_1603'),
    ]

    operations = [
    ]
