# Generated by Django 5.2.1 on 2025-05-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_collection_member_favorite_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', '男'), ('female', '女'), ('other', '不提供')], max_length=10, null=True),
        ),
    ]
