# Generated by Django 5.2.1 on 2025-06-05 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_remove_collection_unique_member_product_and_more'),
        ('products', '0012_product_deleted_at_alter_product_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='products.product'),
        ),
    ]
