# Generated by Django 5.2.1 on 2025-05-19 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_store'),
        ('products', '0009_alter_product_image'),
    ]

    operations = [
    ]
