# Generated by Django 5.2.1 on 2025-05-19 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='inventory',
        ),
    ]
