# Generated by Django 5.2.1 on 2025-06-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='calories',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
